import type { Course, CourseFilterParams } from './types';

export const MOCK_COURSES: Course[] = [
  {
    id: 'crs-001',
    slug: 'foundations-of-sports-nutrition',
    title: 'Foundations of Sports Nutrition',
    shortDescription: 'Master the science of eating for performance, recovery, and body composition.',
    description:
      'This beginner-friendly course covers the essentials of sports nutrition from the ground up. You\'ll learn how macronutrients fuel different types of exercise, when and what to eat around workouts, how to calculate your caloric needs, and how to read supplement labels critically. By the end, you\'ll have a personalised nutrition framework ready to implement immediately.',
    category: 'nutrition',
    level: 'beginner',
    badgeTier: 'bronze',
    instructorName: 'Dr. Kavitha Nair',
    instructorTitle: 'Registered Sports Dietitian, MSc Human Nutrition',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    totalLessons: 5,
    totalDuration: '1h 20min',
    rating: 4.8,
    reviewCount: 1243,
    enrolledCount: 8920,
    tags: ['nutrition', 'macros', 'beginner', 'performance'],
    isFeatured: true,
    createdAt: '2026-01-10',
    lessons: [
      {
        id: 'crs-001-l1',
        title: 'Why Nutrition Is the Foundation of Fitness',
        duration: '12 min',
        youtubeVideoId: 'fJ9rUzIMcZQ',
        description: 'Introduction to how food choices directly impact training outcomes and recovery speed.',
      },
      {
        id: 'crs-001-l2',
        title: 'Understanding Macronutrients: Protein, Carbs & Fats',
        duration: '18 min',
        youtubeVideoId: 'VIu6h1EYmJI',
        description: 'Deep dive into the role of each macronutrient in muscle building, energy production, and fat loss.',
      },
      {
        id: 'crs-001-l3',
        title: 'Calculating Your Caloric Needs (TDEE)',
        duration: '14 min',
        youtubeVideoId: 'PqFrmK9h7-k',
        description: 'Step-by-step guide to calculating Total Daily Energy Expenditure and setting a calorie target.',
      },
      {
        id: 'crs-001-l4',
        title: 'Pre & Post-Workout Nutrition Timing',
        duration: '16 min',
        youtubeVideoId: 'f0Y7Q8-nFQw',
        description: 'What to eat before and after exercise to maximise performance and accelerate recovery.',
      },
      {
        id: 'crs-001-l5',
        title: 'Supplements: What Actually Works',
        duration: '20 min',
        youtubeVideoId: 'b9vKFiJ_mD4',
        description: 'Evidence-based review of creatine, protein, caffeine, BCAAs, and popular supplements.',
      },
    ],
  },
  {
    id: 'crs-002',
    slug: 'powerlifting-fundamentals',
    title: 'Powerlifting Fundamentals',
    shortDescription: 'Learn the squat, bench press, and deadlift with perfect technique from certified coaches.',
    description:
      'This course is the definitive beginner guide to the three powerlifts. Each movement is broken down into setup, bracing, descent, and lockout phases with coaching cues and common fault corrections. You\'ll also learn programming basics — sets, reps, and progressive overload — to keep getting stronger every week. No prior weightlifting experience required.',
    category: 'strength-training',
    level: 'beginner',
    badgeTier: 'bronze',
    instructorName: 'Coach Arjun Singh',
    instructorTitle: 'IPF Certified Powerlifting Coach, CSCS',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800',
    totalLessons: 6,
    totalDuration: '2h 05min',
    rating: 4.9,
    reviewCount: 2187,
    enrolledCount: 14300,
    tags: ['powerlifting', 'strength', 'squat', 'deadlift', 'bench-press'],
    isFeatured: true,
    createdAt: '2026-01-20',
    lessons: [
      {
        id: 'crs-002-l1',
        title: 'Introduction to Powerlifting & Safety',
        duration: '10 min',
        youtubeVideoId: 'OldG3IKHd5E',
        description: 'Overview of the sport, gym etiquette, and essential safety principles before touching a barbell.',
      },
      {
        id: 'crs-002-l2',
        title: 'The Squat: Setup, Bracing & Descent',
        duration: '22 min',
        youtubeVideoId: 'ultWZbUMPL8',
        description: 'Foot placement, bar position, bracing the core, and the controlled descent to depth.',
      },
      {
        id: 'crs-002-l3',
        title: 'The Squat: Drive & Common Faults',
        duration: '18 min',
        youtubeVideoId: 'Dy28eq2PjcM',
        description: 'Driving from the bottom, knee tracking, and fixing the most common squat breakdowns.',
      },
      {
        id: 'crs-002-l4',
        title: 'The Bench Press: Arch, Grip & Descent',
        duration: '20 min',
        youtubeVideoId: 'rT7DgCr-3pg',
        description: 'Building a stable arch, grip width, elbow angle, and controlled descent to touch.',
      },
      {
        id: 'crs-002-l5',
        title: 'The Deadlift: Hinge, Setup & Pull',
        duration: '25 min',
        youtubeVideoId: 'op9kVnSso6Q',
        description: 'Hip hinge mechanics, stance, bar path, and a clean lockout. Conventional and sumo variants covered.',
      },
      {
        id: 'crs-002-l6',
        title: 'Programming Your First 12-Week Block',
        duration: '30 min',
        youtubeVideoId: 'CRxBRVKdMgU',
        description: 'How to set training maxes, choose rep schemes, and apply progressive overload week over week.',
      },
    ],
  },
  {
    id: 'crs-003',
    slug: 'hiit-science-and-programming',
    title: 'HIIT Science & Programming',
    shortDescription: 'Design effective HIIT programs backed by exercise science for fat loss and conditioning.',
    description:
      'Go beyond random workouts and learn the science that makes HIIT effective. This intermediate course covers the physiology of high-intensity intervals, how to manipulate work-to-rest ratios, the role of EPOC in fat loss, and how to periodise HIIT training over a 12-week cycle without burning out. Includes templates for three distinct HIIT program styles.',
    category: 'cardio',
    level: 'intermediate',
    badgeTier: 'silver',
    instructorName: 'Priya Sharma',
    instructorTitle: 'Exercise Physiologist, Certified Fitness Instructor',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800',
    totalLessons: 5,
    totalDuration: '1h 45min',
    rating: 4.7,
    reviewCount: 876,
    enrolledCount: 5400,
    tags: ['hiit', 'cardio', 'fat-loss', 'programming', 'conditioning'],
    isNew: true,
    createdAt: '2026-04-01',
    lessons: [
      {
        id: 'crs-003-l1',
        title: 'The Physiology of High-Intensity Exercise',
        duration: '20 min',
        youtubeVideoId: '2MoGxae-zyo',
        description: 'VO2 max, lactate threshold, energy systems — understanding what happens in the body during HIIT.',
      },
      {
        id: 'crs-003-l2',
        title: 'Work-to-Rest Ratios and Interval Types',
        duration: '18 min',
        youtubeVideoId: '7kgZnJqDhAw',
        description: 'Tabata, 30/30, EMOM, AMRAP — the science behind different interval structures and when to use each.',
      },
      {
        id: 'crs-003-l3',
        title: 'EPOC and Fat Loss Mechanisms',
        duration: '22 min',
        youtubeVideoId: 'vSSkDos2hzo',
        description: 'How excess post-exercise oxygen consumption (EPOC) drives continued calorie burn after training.',
      },
      {
        id: 'crs-003-l4',
        title: 'Periodising HIIT Over a 12-Week Cycle',
        duration: '25 min',
        youtubeVideoId: 'hVAtkDnkv8E',
        description: 'Structuring volume, intensity, and frequency across a training block to avoid plateaus and overtraining.',
      },
      {
        id: 'crs-003-l5',
        title: 'Sample Programs: Beginner, Fat Loss, Athletic',
        duration: '20 min',
        youtubeVideoId: 'ml6cT4AZdqI',
        description: 'Walk-through of three complete HIIT program templates with coaching notes.',
      },
    ],
  },
  {
    id: 'crs-004',
    slug: 'mindful-movement-yoga-for-athletes',
    title: 'Mindful Movement — Yoga for Athletes',
    shortDescription: 'Targeted yoga and breathwork practices to enhance recovery, flexibility, and focus.',
    description:
      'Designed specifically for athletes and active individuals, this course addresses the unique flexibility, mobility, and recovery needs that arise from heavy training. You\'ll learn targeted hip-opener sequences, thoracic spine mobility flows, shoulder stability routines, and pranayama techniques that activate the parasympathetic nervous system for faster recovery.',
    category: 'mindfulness',
    level: 'beginner',
    badgeTier: 'bronze',
    instructorName: 'Swami Arjun Dev',
    instructorTitle: 'E-RYT 500, 30 Years Teaching Experience',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    totalLessons: 4,
    totalDuration: '1h 10min',
    rating: 4.9,
    reviewCount: 2341,
    enrolledCount: 11200,
    tags: ['yoga', 'flexibility', 'recovery', 'mindfulness', 'athletes'],
    createdAt: '2026-02-01',
    lessons: [
      {
        id: 'crs-004-l1',
        title: 'Why Athletes Need Yoga',
        duration: '12 min',
        youtubeVideoId: 'v7AYKMP6rOE',
        description: 'The science of flexibility, injury prevention, and how yoga complements strength and cardio training.',
      },
      {
        id: 'crs-004-l2',
        title: 'Hip Flexor & Hamstring Release Flow',
        duration: '20 min',
        youtubeVideoId: 'g_tea8r9tSg',
        description: 'A 20-minute sequence targeting the hip flexors, glutes, and hamstrings — crucial for runners and lifters.',
      },
      {
        id: 'crs-004-l3',
        title: 'Thoracic Spine & Shoulder Mobility',
        duration: '18 min',
        youtubeVideoId: 'TrEEAQQ1SaE',
        description: 'Open the upper back and shoulders with this targeted flow — essential for overhead athletes.',
      },
      {
        id: 'crs-004-l4',
        title: 'Box Breathing & Parasympathetic Recovery',
        duration: '20 min',
        youtubeVideoId: 'tEmt1Znux58',
        description: 'Pranayama techniques — box breathing, 4-7-8, and nadi shodhana — to down-regulate the nervous system.',
      },
    ],
  },
  {
    id: 'crs-005',
    slug: 'advanced-hypertrophy-programming',
    title: 'Advanced Hypertrophy Programming',
    shortDescription: 'Evidence-based muscle-building strategies for experienced lifters seeking to break plateaus.',
    description:
      'This advanced course applies cutting-edge hypertrophy research to practical programming. Topics include mechanical tension vs. metabolic stress, volume landmarks (MEV, MAV, MRV), exercise selection and variation strategies, deload protocols, and advanced intensification techniques like drop sets, myo-reps, and rest-pause. Designed for lifters with at least 2 years of consistent training.',
    category: 'strength-training',
    level: 'advanced',
    badgeTier: 'gold',
    instructorName: 'Coach Arjun Singh',
    instructorTitle: 'IPF Certified Powerlifting Coach, CSCS',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800',
    totalLessons: 6,
    totalDuration: '3h 00min',
    rating: 4.8,
    reviewCount: 634,
    enrolledCount: 2800,
    tags: ['hypertrophy', 'muscle-building', 'advanced', 'programming', 'periodization'],
    createdAt: '2026-02-15',
    lessons: [
      {
        id: 'crs-005-l1',
        title: 'The Science of Muscle Growth (2026 Update)',
        duration: '28 min',
        youtubeVideoId: 'WO7_TjADpQ8',
        description: 'Updated review of hypertrophy mechanisms: mechanical tension, metabolic stress, and muscle damage.',
      },
      {
        id: 'crs-005-l2',
        title: 'Volume Landmarks: MEV, MAV, MRV Explained',
        duration: '30 min',
        youtubeVideoId: 'fJ9rUzIMcZQ',
        description: 'How to find your minimum, adaptive, and maximum recoverable volumes for each muscle group.',
      },
      {
        id: 'crs-005-l3',
        title: 'Exercise Selection & Variation Protocols',
        duration: '25 min',
        youtubeVideoId: 'VIu6h1EYmJI',
        description: 'When to use compound vs. isolation exercises and how to rotate variations to avoid accommodation.',
      },
      {
        id: 'crs-005-l4',
        title: 'Advanced Intensification Techniques',
        duration: '35 min',
        youtubeVideoId: 'PqFrmK9h7-k',
        description: 'Drop sets, myo-reps, rest-pause, pre-exhaust, and forced reps — when and how to use each safely.',
      },
      {
        id: 'crs-005-l5',
        title: 'Deload Protocols & Managing Fatigue',
        duration: '22 min',
        youtubeVideoId: 'f0Y7Q8-nFQw',
        description: 'Reactive vs. planned deloads, what to reduce (volume, intensity, or frequency), and recovery metrics.',
      },
      {
        id: 'crs-005-l6',
        title: 'Building Your Annual Periodisation Plan',
        duration: '40 min',
        youtubeVideoId: 'b9vKFiJ_mD4',
        description: 'Structuring hypertrophy, strength, and peaking phases over a 52-week calendar.',
      },
    ],
  },
  {
    id: 'crs-006',
    slug: 'active-recovery-and-regeneration',
    title: 'Active Recovery & Regeneration',
    shortDescription: 'Science-backed recovery methods to train harder, reduce injury risk, and feel better.',
    description:
      'Recovery is where adaptation happens — this intermediate course teaches you to use it strategically. Covering foam rolling protocols, active recovery session design, sleep optimisation for athletes, cold and heat therapy, and HRV-guided recovery decisions, you\'ll learn to treat recovery as a performance tool rather than an afterthought.',
    category: 'recovery',
    level: 'intermediate',
    badgeTier: 'silver',
    instructorName: 'Dr. Kavitha Nair',
    instructorTitle: 'Registered Sports Dietitian, MSc Human Nutrition',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    totalLessons: 5,
    totalDuration: '1h 55min',
    rating: 4.6,
    reviewCount: 512,
    enrolledCount: 3700,
    tags: ['recovery', 'sleep', 'foam-rolling', 'HRV', 'mobility'],
    createdAt: '2026-03-05',
    lessons: [
      {
        id: 'crs-006-l1',
        title: 'Recovery 101: Why It\'s a Performance Tool',
        duration: '15 min',
        youtubeVideoId: 'OldG3IKHd5E',
        description: 'Understanding supercompensation, training stress, and why more training without recovery leads to decline.',
      },
      {
        id: 'crs-006-l2',
        title: 'Foam Rolling, Massage & Myofascial Release',
        duration: '22 min',
        youtubeVideoId: 'ultWZbUMPL8',
        description: 'Evidence-based foam rolling protocols and when to use massage tools for maximum benefit.',
      },
      {
        id: 'crs-006-l3',
        title: 'Sleep Optimisation for Athletes',
        duration: '28 min',
        youtubeVideoId: 'Dy28eq2PjcM',
        description: 'Sleep architecture, sleep hygiene strategies, napping, and the impact of poor sleep on performance.',
      },
      {
        id: 'crs-006-l4',
        title: 'Cold & Heat Therapy Protocols',
        duration: '25 min',
        youtubeVideoId: 'rT7DgCr-3pg',
        description: 'Cold water immersion, contrast therapy, sauna protocols — what the evidence says and how to apply it.',
      },
      {
        id: 'crs-006-l5',
        title: 'HRV Monitoring and Auto-Regulation',
        duration: '25 min',
        youtubeVideoId: 'op9kVnSso6Q',
        description: 'Using heart rate variability to make daily training decisions and prevent overtraining.',
      },
    ],
  },
  {
    id: 'crs-007',
    slug: 'biomechanics-for-coaches',
    title: 'Biomechanics for Coaches',
    shortDescription: 'Apply biomechanical principles to improve technique, prevent injury, and enhance performance.',
    description:
      'An intermediate-to-advanced course for coaches and serious athletes who want to understand the mechanics behind human movement. Topics include joint kinematics, force vectors, levers in the body, ground reaction forces, and how to perform basic movement screenings. Includes analysis of common sport movements: sprinting, jumping, throwing, and lifting.',
    category: 'sports-science',
    level: 'intermediate',
    badgeTier: 'silver',
    instructorName: 'Priya Sharma',
    instructorTitle: 'Exercise Physiologist, Certified Fitness Instructor',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=800',
    totalLessons: 5,
    totalDuration: '2h 20min',
    rating: 4.7,
    reviewCount: 298,
    enrolledCount: 1800,
    tags: ['biomechanics', 'coaching', 'sports-science', 'technique', 'injury-prevention'],
    isNew: true,
    createdAt: '2026-04-10',
    lessons: [
      {
        id: 'crs-007-l1',
        title: 'Introduction to Human Biomechanics',
        duration: '20 min',
        youtubeVideoId: 'CRxBRVKdMgU',
        description: 'Key terms, planes of motion, joint types, and why biomechanics matters for coaches.',
      },
      {
        id: 'crs-007-l2',
        title: 'Forces, Levers, and Torque in Movement',
        duration: '30 min',
        youtubeVideoId: '2MoGxae-zyo',
        description: 'How external and internal forces interact with body levers to produce or resist motion.',
      },
      {
        id: 'crs-007-l3',
        title: 'Gait Analysis: Walking and Running',
        duration: '28 min',
        youtubeVideoId: '7kgZnJqDhAw',
        description: 'Phases of the gait cycle, common deviations, and practical cues to correct running mechanics.',
      },
      {
        id: 'crs-007-l4',
        title: 'Movement Screening Tools for Coaches',
        duration: '25 min',
        youtubeVideoId: 'vSSkDos2hzo',
        description: 'FMS and basic functional movement screens — how to conduct them and interpret results.',
      },
      {
        id: 'crs-007-l5',
        title: 'Sport-Specific Mechanics: Lift, Sprint, Jump',
        duration: '37 min',
        youtubeVideoId: 'hVAtkDnkv8E',
        description: 'Biomechanical analysis of the barbell squat, 40m sprint, and vertical jump with coaching applications.',
      },
    ],
  },
  {
    id: 'crs-008',
    slug: 'elite-endurance-periodisation',
    title: 'Elite Endurance Periodisation',
    shortDescription: 'Advanced training periodisation for marathon runners, cyclists, and triathletes.',
    description:
      'This advanced course is designed for serious endurance athletes and coaches aiming to peak for A-race performance. Topics include polarised vs. pyramidal training models, VO2max and lactate threshold development blocks, taper protocols, altitude training theory, and race-day nutrition strategy. Course includes case studies from elite marathon and triathlon programs.',
    category: 'sports-science',
    level: 'advanced',
    badgeTier: 'gold',
    instructorName: 'Priya Sharma',
    instructorTitle: 'Exercise Physiologist, Certified Fitness Instructor',
    instructorAvatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    thumbnailImage: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
    totalLessons: 6,
    totalDuration: '3h 30min',
    rating: 4.9,
    reviewCount: 187,
    enrolledCount: 920,
    tags: ['endurance', 'marathon', 'triathlon', 'periodisation', 'advanced'],
    createdAt: '2026-03-20',
    lessons: [
      {
        id: 'crs-008-l1',
        title: 'Endurance Training Models: Polarised vs. Pyramidal',
        duration: '32 min',
        youtubeVideoId: 'ml6cT4AZdqI',
        description: 'Comparing intensity distribution models used by elite endurance athletes and what science supports.',
      },
      {
        id: 'crs-008-l2',
        title: 'Developing VO2max: Protocols and Progressions',
        duration: '35 min',
        youtubeVideoId: 'WO7_TjADpQ8',
        description: 'High-intensity interval structures proven to raise aerobic ceiling — with programming examples.',
      },
      {
        id: 'crs-008-l3',
        title: 'Lactate Threshold Training Blocks',
        duration: '30 min',
        youtubeVideoId: 'fJ9rUzIMcZQ',
        description: 'Tempo runs, cruise intervals, and sustained effort training to push the lactate inflection point higher.',
      },
      {
        id: 'crs-008-l4',
        title: 'Taper Design for Peak Race Performance',
        duration: '28 min',
        youtubeVideoId: 'VIu6h1EYmJI',
        description: 'How to reduce volume and maintain intensity in the final 2-3 weeks before your A race.',
      },
      {
        id: 'crs-008-l5',
        title: 'Altitude Training: Theory and Application',
        duration: '25 min',
        youtubeVideoId: 'PqFrmK9h7-k',
        description: 'Live High-Train Low methodology, altitude tents, and realistic alternatives for age-group athletes.',
      },
      {
        id: 'crs-008-l6',
        title: 'Race-Day Nutrition Strategy for Endurance Events',
        duration: '40 min',
        youtubeVideoId: 'f0Y7Q8-nFQw',
        description: 'Carbohydrate loading, on-course fuelling rates, hydration strategy, and gut training protocols.',
      },
    ],
  },
];

export function getAllCourses(): Course[] {
  return MOCK_COURSES;
}

export function getCourseBySlug(slug: string): Course | undefined {
  return MOCK_COURSES.find((c) => c.slug === slug);
}

export function getFeaturedCourses(): Course[] {
  return MOCK_COURSES.filter((c) => c.isFeatured);
}

export function filterCourses({ category, level }: CourseFilterParams): Course[] {
  return MOCK_COURSES.filter((c) => {
    if (category && c.category !== category) return false;
    if (level && c.level !== level) return false;
    return true;
  });
}
